language: node_js

node_js:
  - '12'

env:
  - NODE_ENV=TRAVIS_CI

notifications:
  email:
    recipients:
      - denis@baskovsky.ru
    on_success: never
    on_failure: always

git:
  depth: 10
  quiet: true
  submodules: false
  lfs_skip_smudge: true

cache:
  npm: true
  directories:
    - ~/.cache
    - .git/lfs

branches:
  only:
    - master

services:
  - postgresql

before_script:
  - psql -U postgres -d postgres -a -f ./SQL/install.sql

install:
  - npm ci

script:
  - npm test

after_success:
  - npm run report-coverage
