language: node_js

node_js:
  - 10
  - 11

env:
  - NODE_ENV=TRAVIS_CI

git:
  depth: 10
  quiet: true
  submodules: false

cache:
  npm: true
  directories:
    - ~/.cache

branches:
  only:
    - master

install:
  - npm ci

script:
  - npm run lint
  - npm test

after_success:
  - npm run coverage
  - codecov
