os:
  - linux

language: node_js
sudo: false

node_js:
  - '14'

services:
  - postgresql
  - redis-server

addons:
  postgresql: "10"

env:
  global:
    - NODE_ENV=TRAVIS_CI
    - PGUSER=postgres
    - PGHOST=localhost
    - PGPORT=5432
    - PGDATABASE=storydb

notifications:
  email:
    recipients:
      - support@gotointeractive.com
    on_success: never
    on_failure: always

git:
  depth: 10
  quiet: true
  submodules: false
  lfs_skip_smudge: true

cache:
  npm: true
  directories:
    - ~/.cache
    - .git/lfs

branches:
  only:
    - master

install:
  - npm ci

script:
  - npm test

after_success:
  - npm run report:coverage
