os: osx
language: node_js
sudo: false

node_js:
  - '12'

services:
  - postgresql

addons:
  postgresql: "10"

env:
  global:
    - NODE_ENV=TRAVIS_CI
    - PGUSER=postgres
    - PGHOST=localhost
    - PGPORT=5432
    - PGDATABASE=storydb

notifications:
  email:
    recipients:
      - denis@baskovsky.ru
    on_success: never
    on_failure: always

git:
  depth: 10
  quiet: true
  submodules: false
  lfs_skip_smudge: true

cache:
  npm: true
  directories:
    - ~/.cache
    - .git/lfs

branches:
  only:
    - master

install:
  - npm ci

before_script:
  - export PG_DATA=$(brew --prefix)/var/postgres
  - pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}
  - bash SQL/install.sh
  - cat postgres.log
  - git lfs pull

script:
  - npm test

after_success:
  - npm run report-coverage
