# todo перенести оставшуюся логику в ci-cd.yml

cache:
  npm: true
  directories:
    - ~/.cache
    - .git/lfs

branches:
  only:
    - master

install:
  - npm ci

script:
  - npm test

after_success:
  - npm run report:coverage
