language: node_js

node_js:
  - '12'

services:
  - postgresql

addons:
  postgresql: "10"

env:
  global:
    - NODE_ENV=TRAVIS_CI
    - PGUSER=postgres
    - PGHOST=localhost
    - PGPORT=5432
    - PGDATABASE=ProstoDiaryDB

notifications:
  email:
    recipients:
      - denis@baskovsky.ru
    on_success: never
    on_failure: always

git:
  depth: 10
  quiet: true
  submodules: false
  lfs_skip_smudge: true

cache:
  npm: true
  directories:
    - ~/.cache
    - .git/lfs

branches:
  only:
    - master

install:
  - npm ci

before_script:
  - psql --version
  - psql -U postgres -d postgres -a -f ./SQL/install.sql
  - git lfs pull

script:
  - npm test

after_success:
  - npm run report-coverage
