os:
  - linux

language: node_js
sudo: false

node_js:
  - '14'

services:
  - postgresql
  - redis-server

addons:
  postgresql: "10"

env:
  global:
    - NODE_ENV=TRAVIS_CI
    - PGUSER=postgres
    - PGHOST=localhost
    - PGPORT=5432
    - PGDATABASE=storydb

notifications:
  email:
    recipients:
      - support@gotointeractive.com
    on_success: never
    on_failure: always

git:
  depth: 10
  quiet: true
  submodules: false
  lfs_skip_smudge: true

cache:
  npm: true
  directories:
    - ~/.cache
    - .git/lfs

branches:
  only:
    - master

before_install:
  - curl -L https://github.com/github/codeql-action/releases/latest/download/codeql-runner-linux --output codeql-runner
  - chmod +x codeql-runner
  - ./codeql-runner init --languages javascript --config-file .github/codeql/codeql-config.yml --repository gotois/ProstoDiary_bot --github-url https://github.com --github-auth $GITHUB_TOKEN

install:
  - npm ci

before_script:
  - bash scripts/sql.sh
  - git lfs pull

script:
  - npm test

after_success:
  - npm run report:coverage
  - ./codeql-runner analyze --repository gotois/ProstoDiary_bot --github-url https://github.com --github-auth $GITHUB_TOKEN
