codecov:
  token: 6bb966d3-db73-4e01-af23-e1a4129a0f5f

coverage:
  status:
    patch:
      default:
        target: 20%
    project:
      default:
        target: 50%
        threshold: 5%
        base: auto

ignore:
  - "tests/"
  - "ava.config.js"

parsers:
  javascript:
    enable_partials: yes
