codecov:
  token: 6bb966d3-db73-4e01-af23-e1a4129a0f5f

coverage:
  status:
    changes: off
    patch:
      default:
        target: 0%
    project:
      default:
        target: 50%
        threshold: 5%
        base: auto

comment:
  layout: diff
  behavior: once

ignore:
  - "package.json"
  - "**/*.md"
  - "**/*.yml"
  - "tests/"
  - "ava.config.cjs"

parsers:
  javascript:
    enable_partials: yes
