version: '3.9'

services:
  app:
    image: 'qertis/secretary-tg:latest'
    environment:
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - TELEGRAM_DOMAIN=$TELEGRAM_DOMAIN
      - SERVER_HOST=http://web-prod:5555
    networks:
      - global_lan

networks:
  global_lan:
    external: true
