version: '3.9'

services:
  app:
    build:
      context: .
      target: build
    container_name: 'secretary-tg'
    platform: linux/arm64
    environment:
      - TELEGRAM_MINI_APP=$TELEGRAM_MINI_APP
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - TELEGRAM_DOMAIN=$TELEGRAM_DOMAIN
      - TELEGRAM_GATEWAY=$TELEGRAM_GATEWAY
      - SERVER_HOST=http://web-dev:5555
    networks:
      - global_lan

networks:
  global_lan:
    external: true
