version: '3.9'

services:
  app:
    image: "qertis/secretary-tg:latest"
    environment:
      - TELEGRAM_MINI_APP=$TELEGRAM_MINI_APP
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - TELEGRAM_DOMAIN=$TELEGRAM_DOMAIN
      - TELEGRAM_GATEWAY=$TELEGRAM_GATEWAY
      - SERVER_HOST=http://web-prod:5555
      - SERVER_APP=https://archive.gotointeractive.com
    ports:
      - "8888:8888"
    expose:
      - "8888"
    networks:
      - global_lan
      - default

networks:
  global_lan:
    driver: bridge
    external: true
