version: '3.8'

services:
  app:
    build:
      context: .
      target: build
    container_name: 'tg_bot'
    environment:
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - DOMAIN=$TELEGRAM_DOMAIN
      - GIC_RPC=$GIC_RPC
      - GIC_USER=$GIC_USER
      - GIC_PASSWORD=$GIC_PASSWORD
