version: '3.8'

services:
  app:
    build:
      context: .
      target: build
    container_name: 'tg_bot'
    environment:
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - TELEGRAM_DOMAIN=$TELEGRAM_DOMAIN
      - GIC_RPC=$GIC_RPC
      - GIC_AUTH=$GIC_AUTH
      - GIC_USER=$GIC_USER
      - GIC_PASSWORD=$GIC_PASSWORD
      - DIALOGFLOW_CREDENTIALS=$DIALOGFLOW_CREDENTIALS
      - DIALOGFLOW_CREDENTIALS_SEARCH=$DIALOGFLOW_CREDENTIALS_SEARCH
      - DIALOGFLOW_PROJECT_ID=$DIALOGFLOW_PROJECT_ID
    networks:
      - global_lan

networks:
  global_lan:
    external: true
