const { NODE_ENV, TELEGRAM_MINI_APP, SERVER_HOST, TELEGRAM_TOKEN, TELEGRAM_DOMAIN } = process.env;

module.exports = {
  get IS_DEV() {
    return NODE_ENV?.toLowerCase()?.startsWith('dev');
  },
  TELEGRAM_MINI_APP: TELEGRAM_MINI_APP,
  TELEGRAM_TOKEN: TELEGRAM_TOKEN,
  TELEGRAM_DOMAIN: TELEGRAM_DOMAIN,
  TELEGRAM_MINI_APP_URL: 'https://t.me/gotois_bot/App',
  SERVER_HOST: SERVER_HOST,
};
