const {
  NODE_ENV,
  DIALOGFLOW_CREDENTIALS,
  TELEGRAM_MINI_APP,
  SERVER_HOST,
  SERVER_HOST_USERNAME,
  SERVER_HOST_PASSWORD,
  TELEGRAM_TOKEN,
  TELEGRAM_DOMAIN,
} = process.env;

module.exports = {
  get IS_DEV() {
    return NODE_ENV?.toLowerCase()?.startsWith('dev');
  },
  TELEGRAM_MINI_APP: TELEGRAM_MINI_APP,
  TELEGRAM_TOKEN: TELEGRAM_TOKEN,
  TELEGRAM_DOMAIN: TELEGRAM_DOMAIN,
  TELEGRAM_MINI_APP_URL: 'https://t.me/gotois_bot/App',
  SERVER_HOST: SERVER_HOST,
  SERVER_HOST_USERNAME: SERVER_HOST_USERNAME,
  SERVER_HOST_PASSWORD: SERVER_HOST_PASSWORD,
  get DIALOGFLOW_CREDENTIALS() {
    return JSON.parse(DIALOGFLOW_CREDENTIALS);
  },
};
