const {
  HOST,
  DATABASE,
  DB_USER,
  DBPORT,
  PASSWORD,
  CORALOGIX_WINSTON_PRIVATE_KEY,
  CORALOGIX_WINSTON_APPLICATION_NAME,
  GOOGLE_APPLICATION_CREDENTIALS,
  TOKEN,
  PORT,
  HEROKU_NAME,
  DIALOGFLOW_CREDENTIALS,
  DIALOGFLOW_PROJECT_ID,
  GOOGLE_MAPS_GEOCODING_API,
  PLOTLY_LOGIN,
  PLOTLY_TOKEN,
  SALT_PASSWORD,
} = process.env;

module.exports = {
  host: HOST,
  database: DATABASE,
  user: DB_USER,
  port: DBPORT,
  password: PASSWORD,
  
  CORALOGIX_WINSTON_PRIVATE_KEY,
  CORALOGIX_WINSTON_APPLICATION_NAME,
  GOOGLE_APPLICATION_CREDENTIALS,
  TOKEN,
  PORT,
  HEROKU_NAME,
  DIALOGFLOW_CREDENTIALS,
  DIALOGFLOW_PROJECT_ID,
  GOOGLE_MAPS_GEOCODING_API,
  PLOTLY_LOGIN,
  PLOTLY_TOKEN,
  SALT_PASSWORD,
  
  get IS_PRODUCTION() {
    return String(process.env.NODE_ENV) === 'production';
  },
  
};
