#!/usr/bin/env node
require('dotenv').config();
const fs = require('fs');
const openapiJsonrpcJsdoc = require('openapi-jsonrpc-jsdoc');
const { SERVER } = require('../src/environment');

(async function main() {
  const data = await openapiJsonrpcJsdoc({
    api: '/api/',
    servers: [
      {
        url: `${SERVER.HOST}:${SERVER.PORT}`,
      },
      {
        url: SERVER.HEROKUAPP,
      },
    ],
    packageUrl: './package.json',
    files: './src/api/v3/*.js',
  });
  data.paths['/'] = {
    get: {
      description: 'index page',
    },
    responses: {
      '200': {
        description: 'OK',
      },
    },
  };
  fs.writeFileSync('docs/openapi.json', JSON.stringify(data, null, 2));
})();
