#!/usr/bin/env node
require('dotenv').config();
const fs = require('fs');
const openapiJsonrpcJsdoc = require('openapi-jsonrpc-jsdoc');
const { SERVER } = require('../src/environment');

(async function main() {
  const data = await openapiJsonrpcJsdoc({
    api: '/api/',
    securitySchemes: {
      BasicAuth: {
        type: 'http',
        scheme: 'basic',
      },
    },
    servers: [
      {
        url: `${SERVER.HOST}:${SERVER.PORT}`,
      },
      {
        url: SERVER.HEROKUAPP,
      },
    ],
    packageUrl: './package.json',
    files: './src/api/v3/*.js',
  });
  // ping
  data.paths['/'] = {
    get: {
      responses: {
        '200': {
          description: 'OK',
          content: {
            'text/plain': {
              schema: {
                type: 'string',
              },
            },
          },
        },
      },
    },
  };
  // todo /id/:uuid/:date
  //  ...
  // todo /mail
  //  ...
  // todo /assistants
  //  ...
  // todo /bot
  //  ...
  fs.writeFileSync('docs/openapi.json', JSON.stringify(data, null, 2));
})();
