#!/usr/bin/env node
require('dotenv').config();
const { IS_CRON } = require('../src/environment');
const logger = require('../src/services/logger.service');
const VzorService = require('../src/services/vzor.service');

(async function main() {
  if (IS_CRON) {
    // todo использовать более умный поиск
    const mailMap = await VzorService.search(['ALL']);
    mailMap.forEach(async (mail) => {
      await mailMap.read(mail);
    });
    logger.log('info', 'CRON: Vzor successfully');
    process.exit(0);
  } else {
    new VzorService();
  }
})();
