DROP TYPE IF EXISTS TAG CASCADE;
DROP TYPE IF EXISTS ABSTRACT_TYPE CASCADE;

DROP VIEW IF EXISTS person CASCADE;

DROP TABLE IF EXISTS passport CASCADE;
DROP TABLE IF EXISTS bot CASCADE;
DROP TABLE IF EXISTS ld CASCADE;

DROP TABLE IF EXISTS abstract CASCADE;
DROP TABLE IF EXISTS message CASCADE;
